### PR TITLE
Enable renovate (further config to come)

### LINKED ISSUE #153: [Project PIXL] Set up `renovate` for automated dependency management
### Definition of Done / Acceptance Criteria

[Follow paddy's instructions](https://github.com/UCL-ARC/.github/blob/main/renovate/README.md)

- [x] Installed [renovate](https://github.com/renovatebot/renovate) GitHub app on [UCLH-Foundry/PIXL](https://github.com/UCLH-Foundry/PIXL)
- [ ] Configured `renovate` to our needs, started on #391
  - [ ] Docker dependencies (looks like done by default by using ARC's template)
  - [ ] Python depdendencies (looks like done by default by using ARC's template)
- [ ] Process for accepting changes
- [ ] Set up main branch protection or change to [GitHub rulesets](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/about-rulesets) on [UCLH-Foundry/PIXL](https://github.com/UCLH-Foundry/PIXL/settings/rules) to protect `main` branch

### Testing

Increase test coverage to ensure `renovate` doesn't break anything.
We probably *don't* want auto-merging until we're more confident about the tests.

### Documentation

Describe the `renovate` configuration options and why we want them, document the process for accepting changes

### Dependencies

_No response_

### Details and Comments

_No response_

### PR DESCRIPTION
**Pull request by stefpiatek**
When this is enabled in `main`, renovate will create a PR containing further config for us to edit.

need to do the rest of the steps from the issue but should fix #153. Happy for someone else to pick up

### CODE REVIEW

**Comment by jeremyestein** [comment]
Attempting to install Renovate into the PIXL repo (as per https://github.com/apps/renovate ) I get the error `This action must be performed by an organization owner`.

Oddly, the app already appears to be installed (See https://github.com/UCLH-Foundry/PIXL/settings/installations ) although I don't have permission to configure it. But if it's already been installed there should be an "Onboarding PR" that it automatically generates (see https://github.com/renovatebot/tutorial?tab=readme-ov-file#part-2---onboarding ) which doesn't exist. So I don't know what has happened here.

**Comment by paddyroddy** [comment]
Without being an admin of that repo it is hard to tell but yes you need to install the app for that specific repo. Easiest way to double check is go to https://developer.mend.io/github/UCLH-Foundry and check it is listed, i.e.
image

**Comment by jeremyestein** [comment]
Thanks. Yes, it's listed. The job logs suggest it's in dry run mode though. Perhaps because it's pointing at main and the renovate config file is only in a different branch? The tutorial doesn't say anything about dry runs. Maybe this is in the settings I can't access?

```
INFO: Repository started
{
  "renovateVersion": "37.368.10"
}

INFO: DRY-RUN: Would commit files to onboarding branch
INFO: Dependency extraction complete
{
  "baseBranch": "main"
  "stats": {
    "managers": {
      "docker-compose": {
        "fileCount": 5,
        "depCount": 7
      },
      "dockerfile": {
        "fileCount": 6,
        "depCount": 6
      },
      "github-actions": {
        "fileCount": 1,
        "depCount": 12
      },
      "pep621": {
        "fileCount": 7,
        "depCount": 101
      }
    },
    "total": {
      "fileCount": 19,
      "depCount": 126
    }
  }
}

INFO: Repository finished
{
  "cloned": true
  "durationMs": 32106
}
```

**Comment by paddyroddy** [comment]
There needs to be some kind of @renovatebot config in the `main` branch. It should have made an onboarding PR - which would be automatically closed if you were to merge a config file in beforehand.

**Review by peshence — APPROVED** [review]

**Comment by milanmlft** [comment]
🚀 ❤️

**Comment by paddyroddy** [comment]
`schedule:monthly` is already set https://github.com/UCL-ARC/.github/blob/79d60db13e5b9c09843626dd242a4e69d2d056ec/renovate/default-config.json#L6

**Pull request merged**
